### PR TITLE
Change to Code

### PR DESCRIPTION
**Pull request by rubinthomas**
I have modified the CMIS Module to reflect to the most updated changes available for the Alfresco CMIS platform.
A lot of code has been re-written with debugging in the DB options.
Additional Taxonomy module has been added to provide tags and categories to match Alfresco in Drupal.

### CODE REVIEW

**Comment by soundasleep** [comment]
I don't agree with removing .editorconfig. It seems that most of these files have had line changes/whitespace changes and it's not possible to see a clear diff on github.com? Can you use editorconfig to ensure whitespace is correct, clean up the whitespace to make smaller diffs, and resubmit the PR?

**Comment by rubinthomas** [comment]
I have added the .editorconfig back and used the same settings to clean up the files.

**Comment by rubinthomas** [comment]
The changes have now been applied. Hopefully I have got it correct this time..

**Comment by soundasleep** [comment]
Thanks for the PR :)

**Pull request merged**
